### ISSUE TITLE
Enable overflow checks in release build

### ISSUE THREAD

**Issue by tzemanovic** [namada-net/namada#1228]
The arithmetic operators have different default behavior in debug (checked, panic on overflow) vs release build (unchecked, wrapping).

We should enable `overflow-checks` by default in release build as it’s a safer thing to do in our settings and the added cost is worth it.

https://doc.rust-lang.org/reference/expressions/operator-expr.html#overflow

**Comment by sug0** [comment]
I guess this makes `overflowing_*` function calls mostly obsolete then, right?
