### ISSUE TITLE
PoS: improve the unbonds display from `bonds` query

### ISSUE THREAD

**Issue by tzemanovic** [namada-net/namada#1236]
thanks @rnbguy  for the report!

Currently, unbonds of bonds that were bonded in different epochs are shown from the `bonds` query like so:

```
$ namada --mode validator unbond --validator validator-0 --amount 10
...
Current epoch: 8.
Amount 4 withdrawable starting from epoch 11.
Amount 3 withdrawable starting from epoch 11.
Amount 3 withdrawable starting from epoch 11.
```

It also prints out older unbonding amount too.
```
$ namada --mode full unbond --validator validator-0 --source Bertha --amount 1
Amount 1 withdrawable starting from epoch 13.
Amount 1 withdrawable starting from epoch 14.
Amount 0 withdrawable starting from epoch 14.
```

**Comment by brentstone** [comment]
So what is the preferred change here? In the first case, to simply have `Amount 10 withdrawable starting from epoch 11` as the only line?

**Comment by rnbguy** [comment]
Yes. (1) aggregating the amounts and (2) printing only the update due the current unbonding request would be nice.

So for the second example, only this single line should be printed.

```
Amount 1 withdrawable starting from epoch 14.
```
