### ISSUE TITLE
PoS - remove "pending" validator state

### ISSUE THREAD

**Issue by tzemanovic** [namada-net/namada#157]
remove "pending" state as done in the spec: https://github.com/anoma/anoma/pull/1070/commits/6791932d8510e09e291325d69eda044d071aecdf

Depends on anoma/namada#18

**Comment by cwgoes** [comment]
@brentstone what's the status of this?

**Comment by brentstone** [comment]
> @brentstone what's the status of this?

Currently it is addressed in #892 since adding the `jailed` state is included in there as well.
