### ISSUE TITLE
Ordering for `Dec` type is buggy

### ISSUE THREAD

**Issue by brentstone** [namada-net/namada#1762]
The ordering for `Dec` types does not work properly for large numbers it seems. An example encountered in the ledger can be summarized with the following lines:
```
let smaller = Dec::from_str("6483947304.195066085701").unwrap();
let larger = Dec::from_str("32418116583.390243854642").unwrap();
assert!(smaller < larger);
```
The above assertion fails.

**Comment by brentstone** [comment]
@batconjurer

**Comment by batconjurer** [comment]
Hah! Indeed! It inherits the ordering from `I256` which obviously does not take the decimal place into account.

**Comment by batconjurer** [comment]
So the `Ord` implementation for `I256` accidentally inherited from the `Ord` implementation on `[u64; 4`], not `Uint([u64; 4])` which is an issue since the `Uint` type is little endian.

**Comment by batconjurer** [comment]
But the ordering would be correct if only the lowest u64 word was used.
