### ISSUE TITLE
Tune RocksDB configuration

### ISSUE THREAD

**Issue by juped** [namada-net/namada#26]
For now, I just want something usable for our upcoming testnet, so I'm cutting this short until after that, but there is a lot of tuning that can be done with RocksDB. In particular, the default settings tend to assume cases very much unlike ours.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201763124532115) by [Unito](https://www.unito.io)

**Comment by cwgoes** [comment]
@yito88 can you take a look at this in conjunction with investigating rocksdb? plus I remember that you have a bunch of database XP :smile:

**Comment by cwgoes** [comment]
Done.
