### ISSUE TITLE
artifacts.heliax.click down? (502 Bad Gateway)

### ISSUE THREAD

**Issue by egasimus** [namada-net/namada#2686]
Hi all, the automatic download of https://artifacts.heliax.click/namada-wasm/vp_implicit.8781c170ad1e3d2bbddc308b77b7a2edda3fff3bc5d746232feec968ee4fe3cd.wasm (and all the other wasms) as part of the node's bootstrap process fails with 502.

Is this known and is there a workaround? (other than building the wasms locally - which has so far failed to produce the same checksums with `rustc 1.70.0 (90c541806 2023-05-31)`, `cargo 1.70.0 (ec8a8a0ca 2023-04-25)` on Linux)

**Comment by Fraccaman** [comment]
temporary problems they should resolve shortly.
