### ISSUE TITLE
DB diffs pruning for new storage keys loops from current block height to first block

### ISSUE THREAD

**Issue by tzemanovic** [namada-net/namada#2955]
For storage keys where we're not keeping diffs we try to prune them starting from a block height `current - 2` (to allow rollback with `current - 1`). When the storage key doesn't have any diff the loop in `fn batch_write_subspace_diff` keeps going all the way to `BlockHeight::first` without ever finding the diff so it's gets worse over time

**Comment by tzemanovic** [comment]
We're writing the diffs to `{height}/old/{storage_key}` and `{height}/new/{storage_key}` and prune the ones that have `persist_diffs = false`, but we don't know if a key actually had a diff without searching for it

**Comment by cwgoes** [comment]
What about:
- Every time we write a key which we know will need to be deleted, add that key to an index scheduled for deletion, e.g. `/keys_to_delete/{height}`
- Each block, read all keys scheduled for deletion, and delete them

Then we should avoid any searching.
