### ISSUE TITLE
Tracking: First stage MASP VP implementation

### ISSUE THREAD

**Issue by juped** [namada-net/namada#62]
* [x] anoma/namada#54 
* [x] anoma/namada#55 
* [ ] anoma/namada#56

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201757896515792/1201762842161939) by [Unito](https://www.unito.io)

**Comment by murisi** [comment]
@cwgoes I believe the first two issues are done. As for the validity predicate itself, I would need to review the code to fully understand its capabilities and see whether it is complete. See: https://github.com/anoma/namada/issues/56#issuecomment-1399450769

**Comment by cwgoes** [comment]
Closed in favour of #56
